### ISSUE TITLE
The entire thing is an issue!

### ISSUE THREAD

**Issue by SharaMint** [ydarissep/Radical-Red-Pokedex#3]
The new site is such a big step backwards from what it was. Not being able to middle click, and open multiple tabs to easily compare mons. Clicking a move only tells you _**brief**_ information, missing what mons learn it and how. Clicking a mon will not show any regional forms or their weight. And it seems to be missing information in general. (or Surge just has an illegal moveset. dunno?)

**Comment by ydarissep** [comment]
https://ydarissep.github.io/Radical-Red-Pokedex/ there, you can right click and open species info in a new tab.
Given that the dex pull data directly from the source code it's unlikely that it's missing any data...
